### ISSUE TITLE
Not able to hindi text in  sublime3 

### ISSUE THREAD

**Issue by jitendra3109** [happypeter/sublime-config#3]
Hey! @happypeter 
 would you like to resolve my issue? Actually, the issues posted on a forum and waiting for respond .
I'm asking similar thought coz you are reading Chinese clearly without broken but I'm getting text broken in Hindi language.
![image](https://cloud.githubusercontent.com/assets/10773353/21952274/aa6c9512-da3d-11e6-9463-0b5f093bd8da.png)

**Comment by happypeter** [comment]
Really not sure what's going on in your case. Sorry
